// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: targetdata.proto

package com.learn.java.protoc;

/**
 * Protobuf type {@code TargetWrapperData}
 */
public final class TargetWrapperData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TargetWrapperData)
    TargetWrapperDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TargetWrapperData.newBuilder() to construct.
  private TargetWrapperData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TargetWrapperData() {
    targetDatas_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TargetWrapperData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TargetWrapperData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              targetDatas_ = new java.util.ArrayList<com.learn.java.protoc.TargetData>();
              mutable_bitField0_ |= 0x00000001;
            }
            targetDatas_.add(
                input.readMessage(com.learn.java.protoc.TargetData.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        targetDatas_ = java.util.Collections.unmodifiableList(targetDatas_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.learn.java.protoc.TargetTransportData.internal_static_TargetWrapperData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.learn.java.protoc.TargetTransportData.internal_static_TargetWrapperData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.learn.java.protoc.TargetWrapperData.class, com.learn.java.protoc.TargetWrapperData.Builder.class);
  }

  public static final int TARGETDATAS_FIELD_NUMBER = 1;
  private java.util.List<com.learn.java.protoc.TargetData> targetDatas_;
  /**
   * <code>repeated .TargetData targetDatas = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.learn.java.protoc.TargetData> getTargetDatasList() {
    return targetDatas_;
  }
  /**
   * <code>repeated .TargetData targetDatas = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.learn.java.protoc.TargetDataOrBuilder> 
      getTargetDatasOrBuilderList() {
    return targetDatas_;
  }
  /**
   * <code>repeated .TargetData targetDatas = 1;</code>
   */
  @java.lang.Override
  public int getTargetDatasCount() {
    return targetDatas_.size();
  }
  /**
   * <code>repeated .TargetData targetDatas = 1;</code>
   */
  @java.lang.Override
  public com.learn.java.protoc.TargetData getTargetDatas(int index) {
    return targetDatas_.get(index);
  }
  /**
   * <code>repeated .TargetData targetDatas = 1;</code>
   */
  @java.lang.Override
  public com.learn.java.protoc.TargetDataOrBuilder getTargetDatasOrBuilder(
      int index) {
    return targetDatas_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < targetDatas_.size(); i++) {
      output.writeMessage(1, targetDatas_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < targetDatas_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, targetDatas_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.learn.java.protoc.TargetWrapperData)) {
      return super.equals(obj);
    }
    com.learn.java.protoc.TargetWrapperData other = (com.learn.java.protoc.TargetWrapperData) obj;

    if (!getTargetDatasList()
        .equals(other.getTargetDatasList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTargetDatasCount() > 0) {
      hash = (37 * hash) + TARGETDATAS_FIELD_NUMBER;
      hash = (53 * hash) + getTargetDatasList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.learn.java.protoc.TargetWrapperData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.java.protoc.TargetWrapperData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.java.protoc.TargetWrapperData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.java.protoc.TargetWrapperData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.java.protoc.TargetWrapperData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.java.protoc.TargetWrapperData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.java.protoc.TargetWrapperData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.learn.java.protoc.TargetWrapperData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.learn.java.protoc.TargetWrapperData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.learn.java.protoc.TargetWrapperData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.learn.java.protoc.TargetWrapperData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.learn.java.protoc.TargetWrapperData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.learn.java.protoc.TargetWrapperData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TargetWrapperData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TargetWrapperData)
      com.learn.java.protoc.TargetWrapperDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.learn.java.protoc.TargetTransportData.internal_static_TargetWrapperData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.learn.java.protoc.TargetTransportData.internal_static_TargetWrapperData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.learn.java.protoc.TargetWrapperData.class, com.learn.java.protoc.TargetWrapperData.Builder.class);
    }

    // Construct using com.learn.java.protoc.TargetWrapperData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTargetDatasFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (targetDatasBuilder_ == null) {
        targetDatas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        targetDatasBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.learn.java.protoc.TargetTransportData.internal_static_TargetWrapperData_descriptor;
    }

    @java.lang.Override
    public com.learn.java.protoc.TargetWrapperData getDefaultInstanceForType() {
      return com.learn.java.protoc.TargetWrapperData.getDefaultInstance();
    }

    @java.lang.Override
    public com.learn.java.protoc.TargetWrapperData build() {
      com.learn.java.protoc.TargetWrapperData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.learn.java.protoc.TargetWrapperData buildPartial() {
      com.learn.java.protoc.TargetWrapperData result = new com.learn.java.protoc.TargetWrapperData(this);
      int from_bitField0_ = bitField0_;
      if (targetDatasBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          targetDatas_ = java.util.Collections.unmodifiableList(targetDatas_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.targetDatas_ = targetDatas_;
      } else {
        result.targetDatas_ = targetDatasBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.learn.java.protoc.TargetWrapperData) {
        return mergeFrom((com.learn.java.protoc.TargetWrapperData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.learn.java.protoc.TargetWrapperData other) {
      if (other == com.learn.java.protoc.TargetWrapperData.getDefaultInstance()) return this;
      if (targetDatasBuilder_ == null) {
        if (!other.targetDatas_.isEmpty()) {
          if (targetDatas_.isEmpty()) {
            targetDatas_ = other.targetDatas_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTargetDatasIsMutable();
            targetDatas_.addAll(other.targetDatas_);
          }
          onChanged();
        }
      } else {
        if (!other.targetDatas_.isEmpty()) {
          if (targetDatasBuilder_.isEmpty()) {
            targetDatasBuilder_.dispose();
            targetDatasBuilder_ = null;
            targetDatas_ = other.targetDatas_;
            bitField0_ = (bitField0_ & ~0x00000001);
            targetDatasBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTargetDatasFieldBuilder() : null;
          } else {
            targetDatasBuilder_.addAllMessages(other.targetDatas_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.learn.java.protoc.TargetWrapperData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.learn.java.protoc.TargetWrapperData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.learn.java.protoc.TargetData> targetDatas_ =
      java.util.Collections.emptyList();
    private void ensureTargetDatasIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        targetDatas_ = new java.util.ArrayList<com.learn.java.protoc.TargetData>(targetDatas_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.learn.java.protoc.TargetData, com.learn.java.protoc.TargetData.Builder, com.learn.java.protoc.TargetDataOrBuilder> targetDatasBuilder_;

    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public java.util.List<com.learn.java.protoc.TargetData> getTargetDatasList() {
      if (targetDatasBuilder_ == null) {
        return java.util.Collections.unmodifiableList(targetDatas_);
      } else {
        return targetDatasBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public int getTargetDatasCount() {
      if (targetDatasBuilder_ == null) {
        return targetDatas_.size();
      } else {
        return targetDatasBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public com.learn.java.protoc.TargetData getTargetDatas(int index) {
      if (targetDatasBuilder_ == null) {
        return targetDatas_.get(index);
      } else {
        return targetDatasBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public Builder setTargetDatas(
        int index, com.learn.java.protoc.TargetData value) {
      if (targetDatasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetDatasIsMutable();
        targetDatas_.set(index, value);
        onChanged();
      } else {
        targetDatasBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public Builder setTargetDatas(
        int index, com.learn.java.protoc.TargetData.Builder builderForValue) {
      if (targetDatasBuilder_ == null) {
        ensureTargetDatasIsMutable();
        targetDatas_.set(index, builderForValue.build());
        onChanged();
      } else {
        targetDatasBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public Builder addTargetDatas(com.learn.java.protoc.TargetData value) {
      if (targetDatasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetDatasIsMutable();
        targetDatas_.add(value);
        onChanged();
      } else {
        targetDatasBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public Builder addTargetDatas(
        int index, com.learn.java.protoc.TargetData value) {
      if (targetDatasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetDatasIsMutable();
        targetDatas_.add(index, value);
        onChanged();
      } else {
        targetDatasBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public Builder addTargetDatas(
        com.learn.java.protoc.TargetData.Builder builderForValue) {
      if (targetDatasBuilder_ == null) {
        ensureTargetDatasIsMutable();
        targetDatas_.add(builderForValue.build());
        onChanged();
      } else {
        targetDatasBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public Builder addTargetDatas(
        int index, com.learn.java.protoc.TargetData.Builder builderForValue) {
      if (targetDatasBuilder_ == null) {
        ensureTargetDatasIsMutable();
        targetDatas_.add(index, builderForValue.build());
        onChanged();
      } else {
        targetDatasBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public Builder addAllTargetDatas(
        java.lang.Iterable<? extends com.learn.java.protoc.TargetData> values) {
      if (targetDatasBuilder_ == null) {
        ensureTargetDatasIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, targetDatas_);
        onChanged();
      } else {
        targetDatasBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public Builder clearTargetDatas() {
      if (targetDatasBuilder_ == null) {
        targetDatas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        targetDatasBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public Builder removeTargetDatas(int index) {
      if (targetDatasBuilder_ == null) {
        ensureTargetDatasIsMutable();
        targetDatas_.remove(index);
        onChanged();
      } else {
        targetDatasBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public com.learn.java.protoc.TargetData.Builder getTargetDatasBuilder(
        int index) {
      return getTargetDatasFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public com.learn.java.protoc.TargetDataOrBuilder getTargetDatasOrBuilder(
        int index) {
      if (targetDatasBuilder_ == null) {
        return targetDatas_.get(index);  } else {
        return targetDatasBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public java.util.List<? extends com.learn.java.protoc.TargetDataOrBuilder> 
         getTargetDatasOrBuilderList() {
      if (targetDatasBuilder_ != null) {
        return targetDatasBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(targetDatas_);
      }
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public com.learn.java.protoc.TargetData.Builder addTargetDatasBuilder() {
      return getTargetDatasFieldBuilder().addBuilder(
          com.learn.java.protoc.TargetData.getDefaultInstance());
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public com.learn.java.protoc.TargetData.Builder addTargetDatasBuilder(
        int index) {
      return getTargetDatasFieldBuilder().addBuilder(
          index, com.learn.java.protoc.TargetData.getDefaultInstance());
    }
    /**
     * <code>repeated .TargetData targetDatas = 1;</code>
     */
    public java.util.List<com.learn.java.protoc.TargetData.Builder> 
         getTargetDatasBuilderList() {
      return getTargetDatasFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.learn.java.protoc.TargetData, com.learn.java.protoc.TargetData.Builder, com.learn.java.protoc.TargetDataOrBuilder> 
        getTargetDatasFieldBuilder() {
      if (targetDatasBuilder_ == null) {
        targetDatasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.learn.java.protoc.TargetData, com.learn.java.protoc.TargetData.Builder, com.learn.java.protoc.TargetDataOrBuilder>(
                targetDatas_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        targetDatas_ = null;
      }
      return targetDatasBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TargetWrapperData)
  }

  // @@protoc_insertion_point(class_scope:TargetWrapperData)
  private static final com.learn.java.protoc.TargetWrapperData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.learn.java.protoc.TargetWrapperData();
  }

  public static com.learn.java.protoc.TargetWrapperData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TargetWrapperData>
      PARSER = new com.google.protobuf.AbstractParser<TargetWrapperData>() {
    @java.lang.Override
    public TargetWrapperData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TargetWrapperData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TargetWrapperData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TargetWrapperData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.learn.java.protoc.TargetWrapperData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

