// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: targetdata.proto

package com.learn.java.protoc;

/**
 * Protobuf type {@code TargetData}
 */
public final class TargetData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TargetData)
    TargetDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TargetData.newBuilder() to construct.
  private TargetData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TargetData() {
    targetCode_ = "";
    targetType_ = "";
    targetValue_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TargetData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TargetData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            targetCode_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            targetType_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            targetValue_ = s;
            break;
          }
          case 34: {
            com.learn.java.protoc.TargetAlarmData.Builder subBuilder = null;
            if (alarmData_ != null) {
              subBuilder = alarmData_.toBuilder();
            }
            alarmData_ = input.readMessage(com.learn.java.protoc.TargetAlarmData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(alarmData_);
              alarmData_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.learn.java.protoc.TargetTransportData.internal_static_TargetData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.learn.java.protoc.TargetTransportData.internal_static_TargetData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.learn.java.protoc.TargetData.class, com.learn.java.protoc.TargetData.Builder.class);
  }

  public static final int TARGET_CODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object targetCode_;
  /**
   * <code>string target_code = 1;</code>
   * @return The targetCode.
   */
  @java.lang.Override
  public java.lang.String getTargetCode() {
    java.lang.Object ref = targetCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetCode_ = s;
      return s;
    }
  }
  /**
   * <code>string target_code = 1;</code>
   * @return The bytes for targetCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetCodeBytes() {
    java.lang.Object ref = targetCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGET_TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object targetType_;
  /**
   * <code>string target_type = 2;</code>
   * @return The targetType.
   */
  @java.lang.Override
  public java.lang.String getTargetType() {
    java.lang.Object ref = targetType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetType_ = s;
      return s;
    }
  }
  /**
   * <code>string target_type = 2;</code>
   * @return The bytes for targetType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetTypeBytes() {
    java.lang.Object ref = targetType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGET_VALUE_FIELD_NUMBER = 3;
  private volatile java.lang.Object targetValue_;
  /**
   * <code>string target_value = 3;</code>
   * @return The targetValue.
   */
  @java.lang.Override
  public java.lang.String getTargetValue() {
    java.lang.Object ref = targetValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetValue_ = s;
      return s;
    }
  }
  /**
   * <code>string target_value = 3;</code>
   * @return The bytes for targetValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetValueBytes() {
    java.lang.Object ref = targetValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALARM_DATA_FIELD_NUMBER = 4;
  private com.learn.java.protoc.TargetAlarmData alarmData_;
  /**
   * <code>.TargetAlarmData alarm_data = 4;</code>
   * @return Whether the alarmData field is set.
   */
  @java.lang.Override
  public boolean hasAlarmData() {
    return alarmData_ != null;
  }
  /**
   * <code>.TargetAlarmData alarm_data = 4;</code>
   * @return The alarmData.
   */
  @java.lang.Override
  public com.learn.java.protoc.TargetAlarmData getAlarmData() {
    return alarmData_ == null ? com.learn.java.protoc.TargetAlarmData.getDefaultInstance() : alarmData_;
  }
  /**
   * <code>.TargetAlarmData alarm_data = 4;</code>
   */
  @java.lang.Override
  public com.learn.java.protoc.TargetAlarmDataOrBuilder getAlarmDataOrBuilder() {
    return getAlarmData();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, targetCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, targetType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetValue_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, targetValue_);
    }
    if (alarmData_ != null) {
      output.writeMessage(4, getAlarmData());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, targetCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, targetType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetValue_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, targetValue_);
    }
    if (alarmData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getAlarmData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.learn.java.protoc.TargetData)) {
      return super.equals(obj);
    }
    com.learn.java.protoc.TargetData other = (com.learn.java.protoc.TargetData) obj;

    if (!getTargetCode()
        .equals(other.getTargetCode())) return false;
    if (!getTargetType()
        .equals(other.getTargetType())) return false;
    if (!getTargetValue()
        .equals(other.getTargetValue())) return false;
    if (hasAlarmData() != other.hasAlarmData()) return false;
    if (hasAlarmData()) {
      if (!getAlarmData()
          .equals(other.getAlarmData())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TARGET_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getTargetCode().hashCode();
    hash = (37 * hash) + TARGET_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTargetType().hashCode();
    hash = (37 * hash) + TARGET_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getTargetValue().hashCode();
    if (hasAlarmData()) {
      hash = (37 * hash) + ALARM_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getAlarmData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.learn.java.protoc.TargetData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.java.protoc.TargetData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.java.protoc.TargetData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.java.protoc.TargetData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.java.protoc.TargetData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.java.protoc.TargetData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.java.protoc.TargetData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.learn.java.protoc.TargetData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.learn.java.protoc.TargetData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.learn.java.protoc.TargetData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.learn.java.protoc.TargetData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.learn.java.protoc.TargetData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.learn.java.protoc.TargetData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TargetData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TargetData)
      com.learn.java.protoc.TargetDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.learn.java.protoc.TargetTransportData.internal_static_TargetData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.learn.java.protoc.TargetTransportData.internal_static_TargetData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.learn.java.protoc.TargetData.class, com.learn.java.protoc.TargetData.Builder.class);
    }

    // Construct using com.learn.java.protoc.TargetData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      targetCode_ = "";

      targetType_ = "";

      targetValue_ = "";

      if (alarmDataBuilder_ == null) {
        alarmData_ = null;
      } else {
        alarmData_ = null;
        alarmDataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.learn.java.protoc.TargetTransportData.internal_static_TargetData_descriptor;
    }

    @java.lang.Override
    public com.learn.java.protoc.TargetData getDefaultInstanceForType() {
      return com.learn.java.protoc.TargetData.getDefaultInstance();
    }

    @java.lang.Override
    public com.learn.java.protoc.TargetData build() {
      com.learn.java.protoc.TargetData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.learn.java.protoc.TargetData buildPartial() {
      com.learn.java.protoc.TargetData result = new com.learn.java.protoc.TargetData(this);
      result.targetCode_ = targetCode_;
      result.targetType_ = targetType_;
      result.targetValue_ = targetValue_;
      if (alarmDataBuilder_ == null) {
        result.alarmData_ = alarmData_;
      } else {
        result.alarmData_ = alarmDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.learn.java.protoc.TargetData) {
        return mergeFrom((com.learn.java.protoc.TargetData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.learn.java.protoc.TargetData other) {
      if (other == com.learn.java.protoc.TargetData.getDefaultInstance()) return this;
      if (!other.getTargetCode().isEmpty()) {
        targetCode_ = other.targetCode_;
        onChanged();
      }
      if (!other.getTargetType().isEmpty()) {
        targetType_ = other.targetType_;
        onChanged();
      }
      if (!other.getTargetValue().isEmpty()) {
        targetValue_ = other.targetValue_;
        onChanged();
      }
      if (other.hasAlarmData()) {
        mergeAlarmData(other.getAlarmData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.learn.java.protoc.TargetData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.learn.java.protoc.TargetData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object targetCode_ = "";
    /**
     * <code>string target_code = 1;</code>
     * @return The targetCode.
     */
    public java.lang.String getTargetCode() {
      java.lang.Object ref = targetCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string target_code = 1;</code>
     * @return The bytes for targetCode.
     */
    public com.google.protobuf.ByteString
        getTargetCodeBytes() {
      java.lang.Object ref = targetCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string target_code = 1;</code>
     * @param value The targetCode to set.
     * @return This builder for chaining.
     */
    public Builder setTargetCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      targetCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string target_code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetCode() {
      
      targetCode_ = getDefaultInstance().getTargetCode();
      onChanged();
      return this;
    }
    /**
     * <code>string target_code = 1;</code>
     * @param value The bytes for targetCode to set.
     * @return This builder for chaining.
     */
    public Builder setTargetCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      targetCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object targetType_ = "";
    /**
     * <code>string target_type = 2;</code>
     * @return The targetType.
     */
    public java.lang.String getTargetType() {
      java.lang.Object ref = targetType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string target_type = 2;</code>
     * @return The bytes for targetType.
     */
    public com.google.protobuf.ByteString
        getTargetTypeBytes() {
      java.lang.Object ref = targetType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string target_type = 2;</code>
     * @param value The targetType to set.
     * @return This builder for chaining.
     */
    public Builder setTargetType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      targetType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string target_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetType() {
      
      targetType_ = getDefaultInstance().getTargetType();
      onChanged();
      return this;
    }
    /**
     * <code>string target_type = 2;</code>
     * @param value The bytes for targetType to set.
     * @return This builder for chaining.
     */
    public Builder setTargetTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      targetType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object targetValue_ = "";
    /**
     * <code>string target_value = 3;</code>
     * @return The targetValue.
     */
    public java.lang.String getTargetValue() {
      java.lang.Object ref = targetValue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string target_value = 3;</code>
     * @return The bytes for targetValue.
     */
    public com.google.protobuf.ByteString
        getTargetValueBytes() {
      java.lang.Object ref = targetValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string target_value = 3;</code>
     * @param value The targetValue to set.
     * @return This builder for chaining.
     */
    public Builder setTargetValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      targetValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string target_value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetValue() {
      
      targetValue_ = getDefaultInstance().getTargetValue();
      onChanged();
      return this;
    }
    /**
     * <code>string target_value = 3;</code>
     * @param value The bytes for targetValue to set.
     * @return This builder for chaining.
     */
    public Builder setTargetValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      targetValue_ = value;
      onChanged();
      return this;
    }

    private com.learn.java.protoc.TargetAlarmData alarmData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.learn.java.protoc.TargetAlarmData, com.learn.java.protoc.TargetAlarmData.Builder, com.learn.java.protoc.TargetAlarmDataOrBuilder> alarmDataBuilder_;
    /**
     * <code>.TargetAlarmData alarm_data = 4;</code>
     * @return Whether the alarmData field is set.
     */
    public boolean hasAlarmData() {
      return alarmDataBuilder_ != null || alarmData_ != null;
    }
    /**
     * <code>.TargetAlarmData alarm_data = 4;</code>
     * @return The alarmData.
     */
    public com.learn.java.protoc.TargetAlarmData getAlarmData() {
      if (alarmDataBuilder_ == null) {
        return alarmData_ == null ? com.learn.java.protoc.TargetAlarmData.getDefaultInstance() : alarmData_;
      } else {
        return alarmDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.TargetAlarmData alarm_data = 4;</code>
     */
    public Builder setAlarmData(com.learn.java.protoc.TargetAlarmData value) {
      if (alarmDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        alarmData_ = value;
        onChanged();
      } else {
        alarmDataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.TargetAlarmData alarm_data = 4;</code>
     */
    public Builder setAlarmData(
        com.learn.java.protoc.TargetAlarmData.Builder builderForValue) {
      if (alarmDataBuilder_ == null) {
        alarmData_ = builderForValue.build();
        onChanged();
      } else {
        alarmDataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.TargetAlarmData alarm_data = 4;</code>
     */
    public Builder mergeAlarmData(com.learn.java.protoc.TargetAlarmData value) {
      if (alarmDataBuilder_ == null) {
        if (alarmData_ != null) {
          alarmData_ =
            com.learn.java.protoc.TargetAlarmData.newBuilder(alarmData_).mergeFrom(value).buildPartial();
        } else {
          alarmData_ = value;
        }
        onChanged();
      } else {
        alarmDataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.TargetAlarmData alarm_data = 4;</code>
     */
    public Builder clearAlarmData() {
      if (alarmDataBuilder_ == null) {
        alarmData_ = null;
        onChanged();
      } else {
        alarmData_ = null;
        alarmDataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.TargetAlarmData alarm_data = 4;</code>
     */
    public com.learn.java.protoc.TargetAlarmData.Builder getAlarmDataBuilder() {
      
      onChanged();
      return getAlarmDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.TargetAlarmData alarm_data = 4;</code>
     */
    public com.learn.java.protoc.TargetAlarmDataOrBuilder getAlarmDataOrBuilder() {
      if (alarmDataBuilder_ != null) {
        return alarmDataBuilder_.getMessageOrBuilder();
      } else {
        return alarmData_ == null ?
            com.learn.java.protoc.TargetAlarmData.getDefaultInstance() : alarmData_;
      }
    }
    /**
     * <code>.TargetAlarmData alarm_data = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.learn.java.protoc.TargetAlarmData, com.learn.java.protoc.TargetAlarmData.Builder, com.learn.java.protoc.TargetAlarmDataOrBuilder> 
        getAlarmDataFieldBuilder() {
      if (alarmDataBuilder_ == null) {
        alarmDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.learn.java.protoc.TargetAlarmData, com.learn.java.protoc.TargetAlarmData.Builder, com.learn.java.protoc.TargetAlarmDataOrBuilder>(
                getAlarmData(),
                getParentForChildren(),
                isClean());
        alarmData_ = null;
      }
      return alarmDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TargetData)
  }

  // @@protoc_insertion_point(class_scope:TargetData)
  private static final com.learn.java.protoc.TargetData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.learn.java.protoc.TargetData();
  }

  public static com.learn.java.protoc.TargetData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TargetData>
      PARSER = new com.google.protobuf.AbstractParser<TargetData>() {
    @java.lang.Override
    public TargetData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TargetData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TargetData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TargetData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.learn.java.protoc.TargetData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

