// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: targetdata.proto

package com.learn.java.protoc;

/**
 * Protobuf type {@code TargetAlarmData}
 */
public final class TargetAlarmData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TargetAlarmData)
    TargetAlarmDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TargetAlarmData.newBuilder() to construct.
  private TargetAlarmData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TargetAlarmData() {
    alarmType_ = "";
    alarmValue_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TargetAlarmData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TargetAlarmData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            alarmStatus_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            alarmType_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            alarmValue_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.learn.java.protoc.TargetTransportData.internal_static_TargetAlarmData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.learn.java.protoc.TargetTransportData.internal_static_TargetAlarmData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.learn.java.protoc.TargetAlarmData.class, com.learn.java.protoc.TargetAlarmData.Builder.class);
  }

  public static final int ALARM_STATUS_FIELD_NUMBER = 1;
  private boolean alarmStatus_;
  /**
   * <code>bool alarm_status = 1;</code>
   * @return The alarmStatus.
   */
  @java.lang.Override
  public boolean getAlarmStatus() {
    return alarmStatus_;
  }

  public static final int ALARM_TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object alarmType_;
  /**
   * <code>string alarm_type = 2;</code>
   * @return The alarmType.
   */
  @java.lang.Override
  public java.lang.String getAlarmType() {
    java.lang.Object ref = alarmType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alarmType_ = s;
      return s;
    }
  }
  /**
   * <code>string alarm_type = 2;</code>
   * @return The bytes for alarmType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlarmTypeBytes() {
    java.lang.Object ref = alarmType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alarmType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALARM_VALUE_FIELD_NUMBER = 3;
  private volatile java.lang.Object alarmValue_;
  /**
   * <code>string alarm_value = 3;</code>
   * @return The alarmValue.
   */
  @java.lang.Override
  public java.lang.String getAlarmValue() {
    java.lang.Object ref = alarmValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alarmValue_ = s;
      return s;
    }
  }
  /**
   * <code>string alarm_value = 3;</code>
   * @return The bytes for alarmValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlarmValueBytes() {
    java.lang.Object ref = alarmValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alarmValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (alarmStatus_ != false) {
      output.writeBool(1, alarmStatus_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alarmType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, alarmType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alarmValue_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, alarmValue_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (alarmStatus_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, alarmStatus_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alarmType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, alarmType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alarmValue_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, alarmValue_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.learn.java.protoc.TargetAlarmData)) {
      return super.equals(obj);
    }
    com.learn.java.protoc.TargetAlarmData other = (com.learn.java.protoc.TargetAlarmData) obj;

    if (getAlarmStatus()
        != other.getAlarmStatus()) return false;
    if (!getAlarmType()
        .equals(other.getAlarmType())) return false;
    if (!getAlarmValue()
        .equals(other.getAlarmValue())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALARM_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAlarmStatus());
    hash = (37 * hash) + ALARM_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getAlarmType().hashCode();
    hash = (37 * hash) + ALARM_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getAlarmValue().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.learn.java.protoc.TargetAlarmData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.java.protoc.TargetAlarmData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.java.protoc.TargetAlarmData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.java.protoc.TargetAlarmData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.java.protoc.TargetAlarmData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.learn.java.protoc.TargetAlarmData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.learn.java.protoc.TargetAlarmData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.learn.java.protoc.TargetAlarmData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.learn.java.protoc.TargetAlarmData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.learn.java.protoc.TargetAlarmData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.learn.java.protoc.TargetAlarmData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.learn.java.protoc.TargetAlarmData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.learn.java.protoc.TargetAlarmData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TargetAlarmData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TargetAlarmData)
      com.learn.java.protoc.TargetAlarmDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.learn.java.protoc.TargetTransportData.internal_static_TargetAlarmData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.learn.java.protoc.TargetTransportData.internal_static_TargetAlarmData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.learn.java.protoc.TargetAlarmData.class, com.learn.java.protoc.TargetAlarmData.Builder.class);
    }

    // Construct using com.learn.java.protoc.TargetAlarmData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      alarmStatus_ = false;

      alarmType_ = "";

      alarmValue_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.learn.java.protoc.TargetTransportData.internal_static_TargetAlarmData_descriptor;
    }

    @java.lang.Override
    public com.learn.java.protoc.TargetAlarmData getDefaultInstanceForType() {
      return com.learn.java.protoc.TargetAlarmData.getDefaultInstance();
    }

    @java.lang.Override
    public com.learn.java.protoc.TargetAlarmData build() {
      com.learn.java.protoc.TargetAlarmData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.learn.java.protoc.TargetAlarmData buildPartial() {
      com.learn.java.protoc.TargetAlarmData result = new com.learn.java.protoc.TargetAlarmData(this);
      result.alarmStatus_ = alarmStatus_;
      result.alarmType_ = alarmType_;
      result.alarmValue_ = alarmValue_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.learn.java.protoc.TargetAlarmData) {
        return mergeFrom((com.learn.java.protoc.TargetAlarmData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.learn.java.protoc.TargetAlarmData other) {
      if (other == com.learn.java.protoc.TargetAlarmData.getDefaultInstance()) return this;
      if (other.getAlarmStatus() != false) {
        setAlarmStatus(other.getAlarmStatus());
      }
      if (!other.getAlarmType().isEmpty()) {
        alarmType_ = other.alarmType_;
        onChanged();
      }
      if (!other.getAlarmValue().isEmpty()) {
        alarmValue_ = other.alarmValue_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.learn.java.protoc.TargetAlarmData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.learn.java.protoc.TargetAlarmData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean alarmStatus_ ;
    /**
     * <code>bool alarm_status = 1;</code>
     * @return The alarmStatus.
     */
    @java.lang.Override
    public boolean getAlarmStatus() {
      return alarmStatus_;
    }
    /**
     * <code>bool alarm_status = 1;</code>
     * @param value The alarmStatus to set.
     * @return This builder for chaining.
     */
    public Builder setAlarmStatus(boolean value) {
      
      alarmStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool alarm_status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlarmStatus() {
      
      alarmStatus_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object alarmType_ = "";
    /**
     * <code>string alarm_type = 2;</code>
     * @return The alarmType.
     */
    public java.lang.String getAlarmType() {
      java.lang.Object ref = alarmType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alarmType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alarm_type = 2;</code>
     * @return The bytes for alarmType.
     */
    public com.google.protobuf.ByteString
        getAlarmTypeBytes() {
      java.lang.Object ref = alarmType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alarmType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alarm_type = 2;</code>
     * @param value The alarmType to set.
     * @return This builder for chaining.
     */
    public Builder setAlarmType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      alarmType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string alarm_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlarmType() {
      
      alarmType_ = getDefaultInstance().getAlarmType();
      onChanged();
      return this;
    }
    /**
     * <code>string alarm_type = 2;</code>
     * @param value The bytes for alarmType to set.
     * @return This builder for chaining.
     */
    public Builder setAlarmTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      alarmType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object alarmValue_ = "";
    /**
     * <code>string alarm_value = 3;</code>
     * @return The alarmValue.
     */
    public java.lang.String getAlarmValue() {
      java.lang.Object ref = alarmValue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alarmValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alarm_value = 3;</code>
     * @return The bytes for alarmValue.
     */
    public com.google.protobuf.ByteString
        getAlarmValueBytes() {
      java.lang.Object ref = alarmValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alarmValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alarm_value = 3;</code>
     * @param value The alarmValue to set.
     * @return This builder for chaining.
     */
    public Builder setAlarmValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      alarmValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string alarm_value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlarmValue() {
      
      alarmValue_ = getDefaultInstance().getAlarmValue();
      onChanged();
      return this;
    }
    /**
     * <code>string alarm_value = 3;</code>
     * @param value The bytes for alarmValue to set.
     * @return This builder for chaining.
     */
    public Builder setAlarmValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      alarmValue_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TargetAlarmData)
  }

  // @@protoc_insertion_point(class_scope:TargetAlarmData)
  private static final com.learn.java.protoc.TargetAlarmData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.learn.java.protoc.TargetAlarmData();
  }

  public static com.learn.java.protoc.TargetAlarmData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TargetAlarmData>
      PARSER = new com.google.protobuf.AbstractParser<TargetAlarmData>() {
    @java.lang.Override
    public TargetAlarmData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TargetAlarmData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TargetAlarmData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TargetAlarmData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.learn.java.protoc.TargetAlarmData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

