// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: targetdata.proto

package com.learn.java.protoc;

public interface TargetAlarmDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TargetAlarmData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool alarm_status = 1;</code>
   * @return The alarmStatus.
   */
  boolean getAlarmStatus();

  /**
   * <code>string alarm_type = 2;</code>
   * @return The alarmType.
   */
  java.lang.String getAlarmType();
  /**
   * <code>string alarm_type = 2;</code>
   * @return The bytes for alarmType.
   */
  com.google.protobuf.ByteString
      getAlarmTypeBytes();

  /**
   * <code>string alarm_value = 3;</code>
   * @return The alarmValue.
   */
  java.lang.String getAlarmValue();
  /**
   * <code>string alarm_value = 3;</code>
   * @return The bytes for alarmValue.
   */
  com.google.protobuf.ByteString
      getAlarmValueBytes();
}
