// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: targetdata.proto

package com.learn.java.protoc;

public interface TargetWrapperDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TargetWrapperData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .TargetData targetDatas = 1;</code>
   */
  java.util.List<com.learn.java.protoc.TargetData> 
      getTargetDatasList();
  /**
   * <code>repeated .TargetData targetDatas = 1;</code>
   */
  com.learn.java.protoc.TargetData getTargetDatas(int index);
  /**
   * <code>repeated .TargetData targetDatas = 1;</code>
   */
  int getTargetDatasCount();
  /**
   * <code>repeated .TargetData targetDatas = 1;</code>
   */
  java.util.List<? extends com.learn.java.protoc.TargetDataOrBuilder> 
      getTargetDatasOrBuilderList();
  /**
   * <code>repeated .TargetData targetDatas = 1;</code>
   */
  com.learn.java.protoc.TargetDataOrBuilder getTargetDatasOrBuilder(
      int index);
}
